version: "3.7"
services:

  seller:
    build: .
    ports:
      - "5000:80"
    networks:
      - common
    environment:
      - ASPNETCORE_URLS=http://*:80

  product:
    build: .
    ports:
      - "5001:80"
    networks:
      - common
    environment:
      - ASPNETCORE_URLS=http://*:80

networks:
  common: